apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort  # <-- Important pour exposer le service hors du cluster

  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001  # ou 30002, 30003...

#docker build -t ilyesnajjari/movie-service:latest . 
#docker push ilyesnajjari/movie-service:latest
#kubectl rollout restart deployment movie-service
#kubectl apply -f movie-service.yaml
#kubectl apply -f deployment.yaml                                                   
#kubectl get svc movie-service
#minikube ip
#minikube service movie-service
#kubectl get pods
