apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort  # <-- Important pour exposer le service hors du cluster

  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
