apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  type: NodePort  # <-- Important pour exposer le service hors du cluster

  selector:
    app: rating-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002  # ou 30002, 30003...



