apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "⏳ En attente de PostgreSQL..."; sleep 2; done']
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres:5432/filmdb"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "filmdb"
      containers:
        - name: movie-service
          image: ilyesnajjari/movie-service:latest  
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres:5432/filmdb"
